# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GitProfile < Formula
  desc "Manage multiple git identity profiles with a single command"
  homepage "https://github.com/hapiio/git-profile"
  version "0.0.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/hapiio/git-profile/releases/download/v0.0.2/git-profile_darwin_x86_64.tar.gz"
      sha256 "eb45435f369cb9ee63ebb12b4ea83ef2b28ec262478ce8e9537568bdb93d268e"

      define_method(:install) do
        bin.install "git-profile"
        # generate_completions_from_executable runs `git-profile completion <shell>`
        # and writes the output to the correct Homebrew completion directory.
        generate_completions_from_executable(bin/"git-profile", "completion")
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/hapiio/git-profile/releases/download/v0.0.2/git-profile_darwin_arm64.tar.gz"
      sha256 "a32affae8310846c8efa6c6f930be8323458ce2158e5191473b18e1d00bd5a18"

      define_method(:install) do
        bin.install "git-profile"
        # generate_completions_from_executable runs `git-profile completion <shell>`
        # and writes the output to the correct Homebrew completion directory.
        generate_completions_from_executable(bin/"git-profile", "completion")
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/hapiio/git-profile/releases/download/v0.0.2/git-profile_linux_x86_64.tar.gz"
      sha256 "393e15402ed9925496fc43ca7fc8aca2719ca24aad19ef14b96034cffaee3549"
      define_method(:install) do
        bin.install "git-profile"
        # generate_completions_from_executable runs `git-profile completion <shell>`
        # and writes the output to the correct Homebrew completion directory.
        generate_completions_from_executable(bin/"git-profile", "completion")
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/hapiio/git-profile/releases/download/v0.0.2/git-profile_linux_arm64.tar.gz"
      sha256 "e12e9089001327220e44314dc822fc56930efdb126c39b6b79131812b9aca551"
      define_method(:install) do
        bin.install "git-profile"
        # generate_completions_from_executable runs `git-profile completion <shell>`
        # and writes the output to the correct Homebrew completion directory.
        generate_completions_from_executable(bin/"git-profile", "completion")
      end
    end
  end

  test do
    system "#{bin}/git-profile", "version"
  end
end
